#!/usr/bin/env node

// Source: https://github.com/ReactiveX/rxjs/blob/master/tools/make-closure-core.js

var compiler = require('google-closure-compiler-js').compile;
var fs = require('fs');

var source = fs.readFileSync('dist/rxjs-diagrams.js', 'utf8');

var compilerFlags = {
  jsCode: [{src: source}],
  languageIn: 'ES3',
  createSourceMap: true,
};

var output = compiler(compilerFlags);

fs.writeFileSync('dist/rxjs-diagrams.min.js', output.compiledCode, 'utf8');
fs.writeFileSync('dist/rxjs-diagrams.min.js.map', output.sourceMap, 'utf8');
